server:
  error:
    include-stacktrace: on_param

# Establishing the connection with a MySql database.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

